language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: rfIE1knh8gPT4rcXGWDIBqxPNeo+8tJysbWQtXmCjB1XsAzLgnUuZ5uLxQjGhI7RdH7NC6S4CGfBx6xRloa7w/O27Svr7NgO+89pOZIhDwgvqhnjFmij0kRnofxUU9HAvWn1cnPfRUBOlLwb+Vl1J9DzkwpVDXReaJUpopfo+0fgdHXwidsLShZk7tIRQs/QbAvGhPyOh02qp8w6PorwmbNr+VovRrirwhIkZbepHUw/hB0fj2vR/gifEPsnmm3U9c1wR3nb7tisBCxl3yWa1W/q0FJaV/R8zRwKbbZahdPR9CUku3JZWKHBtBwnq5P5eb9HmglALsafzEmNl2t2jJo7wKc99a1Mq50v6XBWzpk2+aNEPXytspyFV89+F9EO/44rSmIc1Yy4Jefsgodtq1KH7HAYU0WdZFmD3TlbuWAZJu2ez/L4eqHQXvDmKDej9DqwWJYaifjuntl8/BQnNxNtr1/ivCdIGgW2smmmQkA3xKWc1JsCOYivOpHFNmv6nhYNbhSjJ8oYtTIpXlSnMr70bkmfJjb7X7T4qUmvZEw9qdTb6hMatV9w6A52jyylSD3wsoJMS/eAf/MrEkL1EJfBais+zAWMq6ecGm/FuOH8zylQ66TaDJ4YRxgTF2XJulHNkoGbVQObt/THkqiLV/otXVOLR1zuh45uN0RPSwA=
  app: fast-savannah-21543
  on:
    repo: JesseR5095/peep-chat